server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jianbo-fly/springcloud-config.git
          search-paths:
           - springcloud-config
          #default-label: master
          username: 1476125669@qq.com
          password: 19950116Tjb
      label: master

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#3366 需要.
# rabbitmq 相关配置,暴露bus刷新配置的断点
management:
  endpoints: #暴露bus刷新配置的断点
    web:
      exposure:
        include: "bus-refresh"

